export const LOG_IN_PENDING = 'LOG_IN_PENDING';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OFF = 'LOG_OFF';

export const GET_MY_SCORES_PENDING = 'GET_MY_SCORES_PENDING';
export const GET_MY_SCORES_SUCCESS = 'GET_MY_SCORES_SUCCESS';
export const GET_MY_SCORES_FAILURE = 'GET_MY_SCORES_FAILURE';

export const UPDATE_MY_SCORES_SUCCESS = 'UPDATE_MY_SCORES_SUCCESS';
export const UPDATE_MY_SCORES_FAILURE = 'UPDATE_MY_SCORES_FAILURE';

export const GET_HIGH_SCORES_PENDING = 'GET_HIGH_SCORES_PENDING';
export const GET_HIGH_SCORES_SUCCESS = 'GET_HIGH_SCORES_SUCCESS';
export const GET_HIGH_SCORES_FAILURE = 'GET_HIGH_SCORES_FAILURE';

export const MAKE_USER_ACCOUNT_PENDING = 'MAKE_USER_ACCOUNT_PENDING';
export const MAKE_USER_ACCOUNT_SUCCESS = 'MAKE_USER_ACCOUNT_SUCCESS';
export const MAKE_USER_ACCOUNT_FAILURE = 'MAKE_USER_ACCOUNT_FAILURE';

export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_FAILURE = 'CHANGE_USER_PASSWORD_FAILURE';
